#
# This source file is part of the Stanford CardinalKit Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

default_platform(:ios)

platform :ios do
  before_all do
    ENV["FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT"] = "5"
    ENV["FASTLANE_XCODEBUILD_SETTINGS_RETRIES"] = "6"
  end

  desc "Build and test"
  lane :test do
    run_tests(
      code_coverage: true,
      derived_data_path: ".derivedData",
      result_bundle: true,
      output_directory: "."
    )
  end

  desc "Build app"
  lane :build do
    build_app(
      derived_data_path: ".derivedData"
    )
  end

  desc "Sign in to the App Store Connect API"
  lane :signin do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_API_KEY_BASE64"],
      is_key_content_base64: true
    )
  end

  desc "Publish a beta release to internal TestFlight testers"
  lane :beta do
    signin
    increment_build_number({
      build_number: latest_testflight_build_number + 1,
      xcodeproj: "TemplateApplication.xcodeproj"
    })
    build
    commit = last_git_commit
    upload_to_testflight(
      distribute_external: true,
      groups: [
        "External Testers"
      ],
      submit_beta_review: true,
      notify_external_testers: true,
      expire_previous_builds: true,
      changelog: commit[:message]
    )
  end
end
