#
# This source file is part of the Stanford HealthGPT project
#
# SPDX-FileCopyrightText: 2023 Stanford University & Project Contributors
#

name: Pull Request

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  buildandtest:
    name: Build and Test Application
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      artifactname: HealthGPT.xcresult
      fastlanelane: test
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
